version: '3.9'

services:
  db:
    image: postgres
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak-container
    environment:
      - KC_DB=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL=jdbc:postgresql://localhost/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  postgres_data:
