version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 8000:5432
    depends_on:
      - flyway

  flyway:
    container_name: flyway
    image: flyway/flyway:7.15.0
    volumes:
      - ./sql:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres-db:5432/postgres
      FLYWAY_USER: keycloak
      FLYWAY_PASSWORD: password
    command:
      - migrate
