INSERT INTO bd_schema.doctor (id, name, first_name, last_name, cellphone, speciality, email)
VALUES
    ('DOC001', 'Dr. Juan Pérez', 'Juan', 'Pérez', '555-1234', 'plastic surgery', 'jperez@example.com'),
    ('DOC002', 'Dr. María Hernández', 'María', 'Hernández', '555-5678', 'plastic surgery', 'mhernandez@example.com'),
    ('DOC003', 'Dr. Ana Sánchez', 'Ana', 'Sánchez', '555-9012', 'plastic surgery', 'asanchez@example.com'),
    ('DOC004', 'Dr. Carlos Gómez', 'Carlos', 'Gómez', '555-3456', 'general medicine', 'cgomez@example.com'),
    ('DOC005', 'Dr. Laura Torres', 'Laura', 'Torres', '555-7890', 'general medicine', 'ltorres@example.com'),
    ('DOC006', 'Dr. Pedro Ramírez', 'Pedro', 'Ramírez', '555-2345', 'general medicine', 'pramirez@example.com'),
    ('DOC007', 'Dr. Sofía Castro', 'Sofía', 'Castro', '555-6789', 'obstetrics and gynecology', 'scastro@example.com'),
    ('DOC008', 'Dr. José Ruiz', 'José', 'Ruiz', '555-0123', 'obstetrics and gynecology', 'jruiz@example.com'),
    ('DOC009', 'Dr. Alicia González', 'Alicia', 'González', '555-4567', 'obstetrics and gynecology', 'agonzalez@example.com'),
    ('DOC010', 'Dr. Luisa Flores', 'Luisa', 'Flores', '555-8901', 'odontology', 'lflores@example.com'),
    ('DOC011', 'Dr. Miguel Álvarez', 'Miguel', 'Álvarez', '555-2345', 'odontology', 'malvarez@example.com'),
    ('DOC012', 'Dr. Ana María Torres', 'Ana María', 'Torres', '555-6789', 'odontology', 'amtorres@example.com'),
    ('DOC013', 'Dr. Juan Ramírez', 'Juan', 'Ramírez', '555-0123', 'ophthalmology', 'jramirez@example.com'),
    ('DOC014', 'Dr. Andrea Salazar', 'Andrea', 'Salazar', '555-4567', 'ophthalmology', 'asalazar@example.com'),
    ('DOC015', 'Dr. Antonio Gutiérrez', 'Antonio', 'Gutiérrez', '555-8901', 'ophthalmology', 'agutierrez@example.com'),
    ('DOC016', 'Dra. Carolina Cruz', 'Carolina', 'Cruz', '555-2345', 'orthorhinolaryngology', 'ccruz@example.com'),
    ('DOC017', 'Dra. Sofía Rodríguez', 'Sofía', 'Rodríguez', '555-6789', 'orthorhinolaryngology', 'srodriguez@example.com'),
    ('DOC018', 'Dr. Jorge González', 'Jorge', 'González', '555-0123', 'orthorhinolaryngology', 'jgonzalez@example.com'),
    ('DOC019', 'Dra. Ana Martínez', 'Ana', 'Martínez', '555-4567', 'pediatrician', 'amartinez@example.com'),
    ('DOC020', 'Dr. Luis Pérez', 'Luis', 'Pérez', '555-8901', 'pediatrician', 'lperez@example.com'),
    ('DOC021', 'Dr. Julia Hernández', 'Julia', 'Hernández', '555-2345', 'pediatrician', 'jhernandez@example.com'),
    ('DOC022', 'Dra. Carmen Torres', 'Carmen', 'Torres', '555-6789', 'traumatology', 'ctorres@example.com'),
    ('DOC023', 'Dr. Manuel García', 'Manuel', 'García', '555-0123', 'traumatology', 'mgarcia@example.com'),
    ('DOC024', 'Dra. Laura Martínez', 'Laura', 'Martínez', '555-4567', 'traumatology', 'lmartinez@example.com'),
    ('DOC025', 'Dr. Enrique Ramírez', 'Enrique', 'Ramírez', '555-8901', 'urology', 'eramirez@example.com'),
    ('DOC026', 'Dr. Julia Álvarez', 'Julia', 'Álvarez', '555-2345', 'urology', 'jalvarez@example.com'),
    ('DOC027', 'Dr. Rafaela Castro', 'Rafaela', 'Castro', '555-6789', 'urology', 'rcastro@example.com');
